# Generated by Django 5.0.6 on 2024-05-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField(null=True)),
                ('password', models.CharField(max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
